### PR TITLE
Added song inserter for inserting gbs song data into rom file, and updated README.md

### PR DESCRIPTION
**Pull request by messmerd**
This will make Deflemask2GB a lot faster and easier to set up and use.

### CODE REVIEW

**Comment by DevEd2** [comment]
Unfortunately I had to revert this because I'm getting a segmentation fault with the song inserter. Mind looking into this?

**Comment by messmerd** [comment]
Hmm... I'll fix it once I get off work

**Comment by messmerd** [comment]
I just tested it on Windows 10 using all of the Deflemask gb demo songs and I didn't get any errors. What gbs file(s) and OS were you using when you got the seg fault?

**Comment by DevEd2** [comment]
I built the Linux version using the Linux subsystem on Windows 10, which is where I got the segfault. I did it like that because there weren't any instructions for installing GCC on Windows (maybe look into that as well?) As for the GBS file, [here](https://cdn.discordapp.com/attachments/291285777722376192/697604318261411960/launch_base_act_2_proto.gbs) is a link to the GBS file I was using when I tested it.

By the way, the RGBDS repository listed in README.md is outdated. The repository is now located [here](https://github.com/rednex/rgbds).

**Comment by messmerd** [comment]
I'm using Mingw-w64's gcc port for Windows. I just tested it with the GBS file you used and it worked fine. Maybe you switched around the command-line arguments when running it? A few hours ago I added some code to prevent people from entering the arguments wrong, but before that there wasn't anything to prevent it. I'm not really sure what else would cause that to happen.

**Comment by messmerd** [comment]
Also, I just updated Deflemask2GB to be compatible with the newest version of rgbds. Some of the asm section names are now obsolete and generate errors when trying to assemble them, so I updated it to the new section names. On Debian, I successfully assembled Deflemask2GB and compiled SongInserter. Then I ran the "tests.sh" script to create ROM files for every Deflemask gb demo song. You can find the results [here](https://applesk.in/Deflemask2GB/Deflemask2GB_demo_songs_debian.tar.gz). It seems to have worked fine. Running these tests on Windows also works for me.

**Pull request merged**
