### PR TITLE
Added SongInserter, added Deflemask demo songs for testing, updated to RGBDS v0.4.0, and updated README

### PR DESCRIPTION
**Pull request by messmerd**
Everything builds and works correctly for me on Windows 10 (using Mingw-w64) and Debian. 
I also incorporated the changes you made to main.asm after the last pull request. 
Please let me know if it works for you. Thanks!

### CODE REVIEW

**Comment by DevEd2** [comment]
SongInserter still isn't working for me on the Windows 10 Linux subsystem. It complains that the base ROM is too small and completely destroys the contents of the base ROM for some reason. Can you please look into this?

**Comment by messmerd** [comment]
@DevEd2 Hmm... That's strange. The base ROM should be 512 KB before and after using SongInserter. What size is it for you before using it? 

I'm going to try using the Linux Subsystem for Windows here on my end. Which Linux distribution are you using?

**Comment by messmerd** [comment]
I just installed Ubuntu 18.04 LTS for Windows using the Windows Subsystem for Linux, and I was able to get everything working successfully. 

This is everything I did: 

Starting in the home directory: 
```
git clone https://github.com/messmerd/Deflemask2GB.git 
sudo apt-get update 
sudo apt-get install byacc flex pkg-config libpng-dev
git clone https://github.com/rednex/rgbds.git
cd ./rgbds/ 
make
sudo make install 
cd ../Deflemask2GB/  
chmod +x ./build.sh
./build.sh 
ls -s rom.gb            ----> Should output '512 rom.gb' 
cp rom.gb ./SongInserter/rom.gb 
cd ./SongInserter/ 
chmod +x ./build.sh 
./build.sh 
chmod +x ./tests.sh 
./tests.sh 
``` 

Afterwards, I typed `\\wsl$` in my Windows Explorer address bar and from there, I found the newly-created ROM files and ran them in BGB to see if they worked correctly. They did.  

Maybe you could try following the steps above to see if you still get any weird issues.

**Comment by DevEd2** [comment]
Closed as of 4b5b0b30d61e7bdc093fd34dfc569933cd32be43, had to manually merge due to a conflict.

**Pull request closed without merging**
